### ISSUE TITLE
Parse all configuration from a single environment variable

### ISSUE THREAD

**Issue by tpimh** [minzig/strapi-plugin-init-admin-user#1]
My suggestion is to provide a simple alternative to `INIT_ADMIN_USERNAME`, `INIT_ADMIN_PASSWORD`, `INIT_ADMIN_FIRSTNAME`, `INIT_ADMIN_LASTNAME` and `INIT_ADMIN_EMAIL`.

For example, we can use a single variable `STRAPI_INIT_ADMIN` with a value of `admin:admin:Admin:Admin:admin@init-strapi-admin.strapi.io`, which would be first checked to contain exactly 4 `:` separators, and then split by `:` into 5 variables. This also would be useful to support `null` usernames and surnames that Strapi supports, but [strapi-plugin-init-admin-user](https://github.com/minzig/strapi-plugin-init-admin-user) doesn't.

**Comment by minzig** [comment]
Hey @tpimh,
I like your idea. However I would prefer it in JSON. 
I will work on it and after testing with new strapi versions I'll give you an update. 
Cheers!

**Comment by minzig** [comment]
Hey @tpimh,
Sorry for the delay. 
This is now possible by using `JSON`.
Example:
```
INIT_ADMIN='{"username": "admin", "password": "admin", "firstname": "Admin", "lastname": "Admin", "email": "admin@init-strapi-admin.strapi.io"}'
```
