### ISSUE TITLE
Role problem

### ISSUE THREAD

**Issue by nebnes** [minzig/strapi-plugin-init-admin-user#4]
When the plugin is installed and env setup : 

I have just one role display : super admin, instead of three : super admin, editor, author.
![image](https://user-images.githubusercontent.com/6035442/211194771-8c1d240b-c34b-43d0-ab50-4516a7e8e901.png)

And I cannot add other role because Strapi open a modal with a message about limitation of community version: 
![image](https://user-images.githubusercontent.com/6035442/211194978-8875be99-8229-4457-91ba-8a025d887030.png)

My .env file : 

```INIT_ADMIN=true
INIT_ADMIN_USERNAME=admin
INIT_ADMIN_FIRSTNAME=admin
INIT_ADMIN_LASTNAME=admin
INIT_ADMIN_PASSWORD=Password123
INIT_ADMIN_EMAIL=mail@mail.com
```
Versions : 
```
strapi : 4.5.5
node : 16.17.0
```

It work fine without the module installed : I have the three roles available. 
Do you know where it comes from?

**Comment by nebnes** [comment]
I find a solution : 
https://github.com/minzig/strapi-plugin-init-admin-user/pull/5

**Comment by minzig** [comment]
Thanks!
