### ISSUE TITLE
Cannot read properties of undefined (reading 'includes')

### ISSUE THREAD

**Issue by Namstel** [minzig/strapi-plugin-init-admin-user#8]
When I don't have the `INIT_ADMIN` env variable, I get the following error after I run `npm run develop`:
`Cannot read properties of undefined (reading 'includes')`

Workaround is to add the variable with no value.

**Comment by minzig** [comment]
Can't reproduce. But I'm glad you find a solution for your problem. 👍

**Comment by exotexot** [comment]
Have the same issue.
I need to have "INIT_ADMIN" in my env otherwise develop crashes.

I'm using the TS version of strapi.
In JS version of strapi in the past I didn't observe this behaviour.
